[workspace]
members = ["projects/*"]
default-members = [
    "projects/graph",
    "projects/graph-types",
    "projects/graph-adjacency-list",
    "projects/graph-adjacency-matrix",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
